insert into animale (id_animale, nome, genere) values  (1, 'aguglia', 'f'), (2, 'airone', 'm'), (3, 'alborella', 'f'),
    (4, 'arlecchino', 'm'), (5, 'alpaca', 'f'), (6, 'anatra', 'f'), (7, 'anemone', 'f'), (8, 'anguilla', 'f'),
    (9, 'antilope', 'f'), (10, 'ape', 'f'), (11, 'aquila', 'f'), (12, 'aragosta', 'f'), (13, 'astice', 'm'),
    (14, 'astore', 'm'), (15, 'avvoltoio', 'm'), (16, 'babbuino', 'm'), (17, 'baco', 'm'), (18, 'bagarozzo', 'm'),
    (19, 'balena', 'f'), (20, 'balenottora', 'f'), (21, 'barbagianni', 'm'), (22, 'barracuda', 'm'), (23, 'basilisco', 'm'),
    (24, 'bassarisco', 'm'), (25, 'biscia', 'f'), (26, 'bisonte', 'm'), (27, 'bue', 'm'), (28, 'bufalo', 'm'),
    (29, 'calamaro', 'm'), (30, 'camaleonte', 'm'), (31, 'cammello', 'm'), (32, 'canguro', 'm'), (33, 'canocchia', 'f'),
    (34, 'capriolo', 'm'), (35, 'caracal', 'm'), (36, 'carpa', 'f'), (37, 'castoro', 'm'), (38, 'cavalletta', 'f'),
    (39, 'cavallo', 'm'), (40, 'cavalluccioMarino', 'm'), (41, 'cernia', 'f'), (42, 'cervo', 'm'), (43, 'chea', 'f'),
    (44, 'chiocciola', 'f'), (45, 'cicala', 'f'), (46, 'cigno', 'm'), (47, 'cinghiale', 'm'), (48, 'civetta', 'f'),
    (49, 'cobra', 'm'), (50, 'coccinella', 'f'), (51, 'coccodrillo', 'm'), (52, 'colibrì', 'm'), (53, 'colomba', 'f'),
    (54, 'colombaccio', 'm'), (55, 'condor', 'm'), (56, 'coyote', 'm'), (57, 'cuculo', 'm'), (58, 'daino', 'm'),
    (59, 'dalmata', 'm'), (60, 'delfino', 'm'), (61, 'dentice', 'm'), (62, 'dingo', 'm'), (63, 'dinosauro', 'm'),
    (64, 'donnola', 'f'), (65, 'drago', 'm'), (66, 'elefante', 'm'), (67, 'emu', 'm'), (68, 'ermellino', 'm'),
    (69, 'euripiga', 'f'), (70, 'facocero', 'm'), (71, 'fagiano', 'm'), (72, 'faina', 'f'), (73, 'falco', 'm'),
    (74, 'faraona', 'f'), (75, 'farfalla', 'f'), (76, 'foca', 'f'), (77, 'formica', 'f'), (78, 'formichiere', 'm'),
    (79, 'fringuello', 'm'), (80, 'gabbiano', 'm'), (81, 'gallina', 'f'), (82, 'gallo', 'm'), (83, 'gambero', 'm'),
    (84, 'gatto', 'm'), (85, 'gazza', 'f'), (86, 'gazzella', 'f'), (87, 'ghepardo', 'm'), (88, 'ghiandaia', 'f'),
    (89, 'ghiro', 'm'), (90, 'giaguaro', 'm'), (91, 'giraffa', 'f'), (92, 'gnu', 'm'), (93, 'gorilla', 'm'),
    (94, 'granchio', 'm'), (95, 'grifone', 'm'), (96, 'grillo', 'm'), (97, 'grillotalpa', 'm'), (98, 'gruccione', 'm'),
    (99, 'guereza', 'f'), (100, 'gufo', 'm'), (101, 'iena', 'f'), (102, 'ignicolore', 'm'), (103, 'iguana', 'f'),
    (104, 'impala', 'f'), (105, 'ippopotamo', 'm'), (106, 'istrice', 'm'), (107, 'jacanaAfricana', 'f'),
    (108, 'kagu', 'm'), (109, 'kiwi', 'm'), (110, 'koala', 'm'), (111, 'kookaburra', 'm'), (112, 'lama', 'm'),
    (113, 'leone', 'm'), (114, 'leopardo', 'm'), (115, 'lepre', 'f'), (116, 'libellula', 'f'), (117, 'limulo', 'm'),
    (118, 'lince', 'f'), (119, 'luccio', 'm'), (120, 'lucciola', 'f'), (121, 'lumaca', 'f'), (122, 'lupo', 'm'),
    (123, 'macaone', 'm'), (124, 'maggiolino', 'm'), (125, 'malmignatta', 'f'), (126, 'mandrillo', 'm'),
    (127, 'mantideReligiosa', 'f'), (128, 'marabù', 'm'), (129, 'martora', 'f'), (130, 'medusa', 'f'),
    (131, 'merluzzo', 'm'), (132, 'moffetta', 'f'), (133, 'muggine', 'm'), (134, 'murena', 'f'), (135, 'nandù', 'm'),
    (136, 'nasello', 'm'), (137, 'nautilo', 'm'), (138, 'necroforo', 'm'), (139, 'numbato', 'm'), (140, 'oca', 'f'),
    (141, 'ocellotto', 'm'), (142, 'okapia', 'f'), (143, 'opliaCerulea', 'f'), (144, 'orango', 'm'), (145, 'orata', 'f'),
    (146, 'oritteropo', 'm'), (147, 'ornitorinco', 'm'), (148, 'orso', 'm'), (149, 'otarda', 'f'), (150, 'otariaOrsina', 'f'),
    (151, 'panda', 'm'), (152, 'pappagallo', 'm'), (153, 'paradisea', 'f'), (154, 'pavone', 'm'), (155, 'pellicano', 'm'),
    (156, 'petauro', 'm'), (157, 'pettazzurro', 'm'), (158, 'picchio', 'm'), (159, 'piranha', 'm'), (160, 'pitone', 'm'),
    (161, 'polpo', 'm'), (162, 'procione', 'm'), (163, 'puma', 'm'), (164, 'punteruolo', 'm'), (165, 'purpuriceno', 'm'),
    (166, 'quaglia', 'f'), (167, 'quertzal', 'm'), (168, 'racoforo', 'm'), (169, 'ramarro', 'm'), (170, 'rampichino', 'm'),
    (171, 'rana', 'f'), (172, 'ratto', 'm'), (173, 'remora', 'f'), (174, 'riccio', 'm'), (175, 'rigogolo', 'm'),
    (176, 'rinoceronte', 'm'), (177, 'rospo', 'm'), (178, 'saccofaringe', 'm'), (179, 'salamandra', 'f'), (180, 'salmerino', 'm'),
    (181, 'salmone', 'm'), (182, 'sardina', 'f'), (183, 'scarabeo', 'm'), (184, 'scimmia', 'f'), (185, 'scoiattolo', 'm'),
    (186, 'scorpione', 'm'), (187, 'seppia', 'f'), (188, 'serpente', 'm'), (189, 'sfinge', 'f'), (190, 'sgombro', 'm'),
    (191, 'sicofante', 'm'), (192, 'sogliola', 'f'), (193, 'spatola', 'f'), (194, 'spigola', 'f'), (195, 'spizaeto', 'm'),
    (196, 'storione', 'm'), (197, 'struzzo', 'm'), (198, 'taccola', 'f'), (199, 'tamandua', 'f'), (200, 'tanagra', 'f'),
    (201, 'tapiro', 'm'), (202, 'tartaruga', 'f'), (203, 'tasso', 'm'), (204, 'tigre', 'f'), (205, 'tonno', 'm'),
    (206, 'topo', 'm'), (207, 'triglia', 'f'), (208, 'trogoneViolaceo', 'm'), (209, 'trota', 'f'), (210, 'tucano', 'm'),
    (211, 'turaco', 'm'), (212, 'uccello', 'm'), (213, 'urania', 'f'), (214, 'usignolo', 'm'), (215, 'vacca', 'f'),
    (216, 'vespa', 'f'), (217, 'vipera', 'f'), (218, 'volpe', 'f'), (219, 'volpino', 'm'), (220, 'vombato', 'm'),
    (221, 'yaguarondi', 'm'), (222, 'yak', 'm'), (223, 'zanzara', 'f'), (224, 'zebra', 'f'), (225, 'zibetto', 'm'),
    (226, 'zigoloTestaNera', 'f');
insert into aggettivo (id_aggettivo, maschile, femminile) values  (1, 'abile', 'abile'), (2, 'abitudinario', 'abitudinaria'),
    (3, 'accogliente', 'accogliente'), (4, 'accomodante', 'accomodante'), (5, 'addolorato', 'addolorata'),
    (6, 'affascinante', 'affascinante'), (7, 'affidabile', 'affidabile'), (8, 'afflitto', 'afflitta'),
    (9, 'aggressivo', 'aggressiva'), (10, 'agitato', 'agitata'), (11, 'allegro', 'allegra'),
    (12, 'alternativo', 'alternativa'), (13, 'altruista', 'altruista'), (14, 'amabile', 'amabile'),
    (15, 'ambizioso', 'ambiziosa'), (16, 'amichevole', 'amichevole'), (17, 'amorevole', 'amorevole'),
    (18, 'antipatico', 'antipatica'), (19, 'apatico', 'apatica'), (20, 'appassionato', 'appassionata'),
    (21, 'apprezzato', 'apprezzata'), (22, 'ardito', 'ardita'), (23, 'armonioso', 'armoniosa'),
    (24, 'arrendevole', 'arrendevole'), (25, 'asociale', 'asociale'), (26, 'astuto', 'astuta'),
    (27, 'attento', 'attenta'), (28, 'audace', 'audace'), (29, 'avaro', 'avara'), (30, 'avveduto', 'avveduta'),
    (31, 'avventato', 'avventata'), (32, 'bello', 'bella'), (33, 'bizzarro', 'bizzarra'), (34, 'bonario', 'bonaria'),
    (35, 'bravo', 'brava'), (36, 'brutto', 'brutta'), (37, 'bugiardo', 'bugiarda'), (38, 'buono', 'buona'),
    (39, 'burbero', 'burbera'), (40, 'calmo', 'calma'), (41, 'capace', 'capace'), (42, 'caparbio', 'caparbia'),
    (43, 'carino', 'carina'), (44, 'carismatico', 'carismatica'), (45, 'cattivo', 'cattiva'),
    (46, 'chiacchierone', 'chiacchierona'), (47, 'chiaro', 'chiara'), (48, 'cinico', 'cinica'),
    (49, 'codardo', 'codarda'), (50, 'coerente', 'coerente'), (51, 'collerico', 'collerica'), (52, 'colto', 'colta'),
    (53, 'compassionevole', 'compassionevole'), (54, 'compiaciuto', 'compiaciuta'), (55, 'comprensivo', 'comprensiva'),
    (56, 'compreso', 'compresa'), (57, 'comune', 'comune'), (58, 'concentrato', 'concentrata'),
    (59, 'conciliante', 'conciliante'), (60, 'conosciuto', 'conosciuta'), (61, 'contentabile', 'contentabile'),
    (62, 'contento', 'contenta'), (63, 'contratto', 'contratta'), (64, 'copione', 'copiona'),
    (65, 'coraggioso', 'coraggiosa'), (66, 'cordiale', 'cordiale'), (67, 'corretto', 'corretta'),
    (68, 'cortese', 'cortese'), (69, 'costante', 'costante'), (70, 'creativo', 'creativa'), (71, 'crudele', 'crudele'),
    (72, 'curioso', 'curiosa'), (73, 'debole', 'debole'), (74, 'deciso', 'decisa'), (75, 'determinato', 'determinata'),
    (76, 'diffidente', 'diffidente'), (77, 'dimesso', 'dimessa'), (78, 'dinamico', 'dinamica'),
    (79, 'diplomatico', 'diplomatica'), (80, 'disattento', 'disattenta'), (81, 'discreto', 'discreta'),
    (82, 'disfattista', 'disfattista'), (83, 'disinteressato', 'disinteressata'), (84, 'disinvolto', 'disinvolta'),
    (85, 'disonesto', 'disonesta'), (86, 'disordinato', 'disordinata'), (87, 'disorganizzato', 'disorganizzata'),
    (88, 'disponibile', 'disponibile'), (89, 'disprezzato', 'disprezzata'), (90, 'distratto', 'distratta'),
    (91, 'disubbidiente', 'disubbidiente'), (92, 'divertente', 'divertente'), (93, 'dolce', 'dolce'),
    (94, 'eccentrico', 'eccentrica'), (95, 'educato', 'educata'), (96, 'egoista', 'egoista'),
    (97, 'elastico', 'elastica'), (98, 'elegante', 'elegante'), (99, 'emotivo', 'emotiva'),
    (100, 'energico', 'energica'), (101, 'enigmatico', 'enigmatica'), (102, 'entusiasta', 'entusiasta'),
    (103, 'equilibrato', 'equilibrata'), (104, 'esauriente', 'esauriente'), (105, 'esigente', 'esigente'),
    (106, 'estroverso', 'estroversa'), (107, 'falzo', 'falza'), (108, 'fastidioso', 'fastidiosa'),
    (109, 'fedele', 'fedele'), (110, 'felice', 'felice'), (111, 'fiacco', 'fiacca'), (112, 'fidato', 'fidata'),
    (113, 'fiducioso', 'fiduciosa'), (114, 'fifone', 'fifona'), (115, 'figo', 'figa'), (116, 'forte', 'forte'),
    (117, 'fortunato', 'fortunata'), (118, 'forzuto', 'forzuta'), (119, 'fragile', 'fragile'), (120, 'freddo', 'fredda'),
    (121, 'frigido', 'frigida'), (122, 'furbo', 'furba'), (123, 'gagliardo', 'gagliarda'), (124, 'garbato', 'garbata'),
    (125, 'geloso', 'gelosa'), (126, 'generoso', 'generosa'), (127, 'gentile', 'gentile'), (128, 'gioioso', 'gioiosa'),
    (129, 'gioviale', 'gioviale'), (130, 'giusto', 'giusta'), (131, 'goffo', 'goffa'), (132, 'gradevole', 'gradevole'),
    (133, 'grazioso', 'graziosa'), (134, 'grezzo', 'grezza'), (135, 'idoneo', 'idonea'), (136, 'ignorante', 'ignorante'),
    (137, 'immaturo', 'immatura'), (138, 'impacciato', 'impacciata'), (139, 'impavido', 'impavida'),
    (140, 'impaziente', 'impaziente'), (141, 'imperfetto', 'imperfetta'), (142, 'impertinente', 'impertinente'),
    (143, 'imperturbabile', 'imperturbabile'), (144, 'importante', 'importante'), (145, 'impotente', 'impotente'),
    (146, 'impreparato', 'impreparata'), (147, 'imprevedibile', 'imprevedibile'), (148, 'imprudente', 'imprudente'),
    (149, 'impulsivo', 'impulsiva'), (150, 'inaffidabile', 'inaffidabile'), (151, 'incantevole', 'incantevole'),
    (152, 'incapace', 'incapace'), (153, 'incerto', 'incerta'), (154, 'incoerente', 'incoerente'),
    (155, 'incompreso', 'incompresa'), (156, 'incontentabile', 'incontentabile'), (157, 'indeciso', 'indecisa'),
    (158, 'indifferente', 'indifferente'), (159, 'indisponibile', 'indisponibile'), (160, 'indulgente', 'indulgente'),
    (161, 'inesperto', 'inesperta'), (162, 'inetto', 'inetta'), (163, 'infedele', 'infedele'),
    (164, 'infelice', 'infelice'), (165, 'inferiore', 'inferiore'), (166, 'ingegnoso', 'ingegnosa'),
    (167, 'ingenuo', 'ingenua'), (168, 'ingrato', 'ingrata'), (169, 'inidoneo', 'inidonea'),
    (170, 'innocuo', 'innocua'), (171, 'inospitale', 'inospitale'), (172, 'insensato', 'insensata'),
    (173, 'insensibile', 'insensibile'), (174, 'insicuro', 'insicura'), (175, 'insignificante', 'insignificante'),
    (176, 'insoddisfatto', 'insoddisfatta'), (177, 'insolente', 'insolente'), (178, 'intelligente', 'intelligente'),
    (179, 'interessante', 'interessante'), (180, 'interessato', 'interessata'), (181, 'intransigente', 'intransigente'),
    (182, 'introverso', 'introversa'), (183, 'inutile', 'inutile'), (184, 'invadente', 'invadente'),
    (185, 'invidioso', 'invidiosa'), (186, 'irrazionale', 'irrazionale'), (187, 'irregolare', 'irregolare'),
    (188, 'irrequieto', 'irrequieta'), (189, 'irresponsabile', 'irresponsabile'), (190, 'istruito', 'istruita'),
    (191, 'laborioso', 'laboriosa'), (192, 'leale', 'leale'), (193, 'lento', 'lenta'), (194, 'libero', 'libera'),
    (195, 'litigioso', 'litigiosa'), (196, 'lontano', 'lontana'), (197, 'loquace', 'loquace'),
    (198, 'lunatico', 'lunatica'), (199, 'magnanimo', 'magnanima'), (200, 'maldestro', 'maldestra'),
    (201, 'maleducato', 'maleducata'), (202, 'malinconico', 'malinconica'), (203, 'malvagio', 'malvagia'),
    (204, 'maturo', 'matura'), (205, 'memore', 'memore'), (206, 'meschino', 'meschina'), (207, 'mesto', 'mesta'),
    (208, 'minchione', 'minchiona'), (209, 'minuzioso', 'minuziosa'), (210, 'misericordioso', 'misericordiosa'),
    (211, 'misterioso', 'misteriosa'), (212, 'mite', 'mite'), (213, 'modesto', 'modesta'), (214, 'naturale', 'naturale'),
    (215, 'negativo', 'negativa'), (216, 'negligente', 'negligente'), (217, 'noioso', 'noiosa'),
    (218, 'noncurante', 'noncurante'), (219, 'normale', 'normale'), (220, 'obbediente', 'obbediente'),
    (221, 'occupato', 'occupata'), (222, 'odioso', 'odiosa'), (223, 'onesto', 'onesta'), (224, 'operoso', 'operosa'),
    (225, 'ordinato', 'ordinata'), (226, 'organizzato', 'organizzata'), (227, 'orgoglioso', 'orgogliosa'),
    (228, 'originale', 'originale'), (229, 'orribile', 'orribile'), (230, 'oscuro', 'oscura'),
    (231, 'ossequioso', 'ossequiosa'), (232, 'ostile', 'ostile'), (233, 'ottimista', 'ottimista'),
    (234, 'ozioso', 'oziosa'), (235, 'pacifico', 'pacifica'), (236, 'partecipe', 'partecipe'),
    (237, 'pauroso', 'paurosa'), (238, 'paziente', 'paziente'), (239, 'pazzo', 'pazza'), (240, 'perdente', 'perdente'),
    (241, 'perfetto', 'perfetta'), (242, 'pericoloso', 'pericolosa'), (243, 'perspicace', 'perspicace'),
    (244, 'pessimista', 'pessimista'), (245, 'piacevole', 'piacevole'), (246, 'pigro', 'pigra'),
    (247, 'positivo', 'positiva'), (248, 'potente', 'potente'), (249, 'povero', 'povera'), (250, 'pratico', 'pratica'),
    (251, 'pregevole', 'pregevole'), (252, 'premuroso', 'premurosa'), (253, 'preparato', 'preparata'),
    (254, 'presuntuoso', 'presuntuosa'), (255, 'prevedibile', 'prevedibile'), (256, 'profumato', 'profumata'),
    (257, 'propositivo', 'propositiva'), (258, 'prudente', 'prudente'), (259, 'pulito', 'pulita'),
    (260, 'puntuale', 'puntuale'), (261, 'puro', 'pura'), (262, 'puzzolente', 'puzzolente'),
    (263, 'radioso', 'radiosa'), (264, 'raffinato', 'raffinata'), (265, 'raggiante', 'raggiante'),
    (266, 'ragionevole', 'ragionevole'), (267, 'razionale', 'razionale'), (268, 'realista', 'realista'),
    (269, 'regolare', 'regolare'), (270, 'repellente', 'repellente'), (271, 'responsabile', 'responsabile'),
    (272, 'ribelle', 'ribelle'), (273, 'ricco', 'ricca'), (274, 'riconoscente', 'riconoscente'),
    (275, 'riflessivo', 'riflessiva'), (276, 'rigido', 'rigida'), (277, 'rilassato', 'rilassata'),
    (278, 'rinunciatario', 'rinunciataria'), (279, 'ripugnante', 'ripugnante'), (280, 'riservato', 'riservata'),
    (281, 'rispettoso', 'rispettosa'), (282, 'ritardatario', 'ritardataria'), (283, 'romantico', 'romantica'),
    (284, 'rozzo', 'rozza'), (285, 'saccente', 'saccente'), (286, 'saggio', 'saggia'), (287, 'savio', 'savia'),
    (288, 'sbagliato', 'sbagliata'), (289, 'scherzoso', 'scherzosa'), (290, 'scialbo', 'scialba'),
    (291, 'sconosciuto', 'sconosciuta'), (292, 'sconsiderato', 'sconsiderata'), (293, 'scontento', 'scontenta'),
    (294, 'scontroso', 'scontrosa'), (295, 'scorbutico', 'scorbutica'), (296, 'scorretto', 'scorretta'),
    (297, 'scortese', 'scortese'), (298, 'scriteriato', 'scriteriata'), (299, 'sdegnato', 'sdegnata'),
    (300, 'sedentario', 'sedentaria'), (301, 'semplice', 'semplice'), (302, 'sensato', 'sensata'),
    (303, 'sensibile', 'sensibile'), (304, 'sereno', 'serena'), (305, 'serioso', 'seriosa'),
    (306, 'sfacciato', 'sfacciata'), (307, 'sfigato', 'sfigata'), (308, 'sfortunato', 'sfortunata'),
    (309, 'sgarbato', 'sgarbata'), (310, 'sgradevole', 'sgradevole'), (311, 'sgraziato', 'sgraziata'),
    (312, 'sicuro', 'sicura'), (313, 'simpatico', 'simpatica'), (314, 'sincero', 'sincera'),
    (315, 'sleale', 'sleale'), (316, 'smemorato', 'smemorata'), (317, 'sociale', 'sociale'),
    (318, 'socievole', 'socievole'), (319, 'soddisfatto', 'soddisfatta'), (320, 'sognatore', 'sognatrice'),
    (321, 'solitario', 'solitaria'), (322, 'solito', 'solita'), (323, 'spavaldo', 'spavalda'), (324, 'spento', 'spenta'),
    (325, 'spietato', 'spietata'), (326, 'spigliato', 'spigliata'), (327, 'splendido', 'splendida'),
    (328, 'sporco', 'sporca'), (329, 'sportivo', 'sportiva'), (330, 'spregevole', 'spregevole'),
    (331, 'sprezzante', 'sprezzante'), (332, 'squilibrato', 'squilibrata'), (333, 'stabile', 'stabile'),
    (334, 'statico', 'statica'), (335, 'stimato', 'stimata'), (336, 'stonato', 'stonata'), (337, 'stordito', 'stordita'),
    (338, 'strano', 'strana'), (339, 'straordinario', 'straordinaria'), (340, 'studioso', 'studiosa'),
    (341, 'stupido', 'stupida'), (342, 'superficiale', 'superficiale'), (343, 'superiore', 'superiore'),
    (344, 'sveglio', 'sveglia'), (345, 'sventato', 'sventata'), (346, 'svergognato', 'svergognata'),
    (347, 'svogliato', 'svogliata'), (348, 'taciturno', 'taciturna'), (349, 'testardo', 'testarda'),
    (350, 'timido', 'timida'), (351, 'timoroso', 'timorosa'), (352, 'tollerante', 'tollerante'),
    (353, 'traditore', 'traditrice'), (354, 'tranquillo', 'tranquilla'), (355, 'trasandato', 'trasandata'),
    (356, 'trepido', 'trepida'), (357, 'triste', 'triste'), (358, 'turbato', 'turbata'),
    (359, 'ubbidiente', 'ubbidiente'), (360, 'umile', 'umile'), (361, 'unico', 'unica'),
    (362, 'vagabondo', 'vagabonda'), (363, 'valoroso', 'valorosa'), (364, 'vanitoso', 'vanitosa'),
    (365, 'veloce', 'veloce'), (366, 'vendicativo', 'vendicativa'), (367, 'vicino', 'vicina'),
    (368, 'vigliacco', 'vigliacca'), (369, 'vincente', 'vincente'), (370, 'violento', 'violenta'),
    (371, 'virtuoso', 'virtuosa'), (372, 'viziato', 'viziata'), (373, 'volenteroso', 'volenterosa'),
    (374, 'volubile', 'volubile');